# Version catalog is a central place for you to declare and version dependencies
# https://docs.gradle.org/current/userguide/platforms.html#sub:version-catalog
# https://docs.gradle.org/current/userguide/platforms.html#sub::toml-dependencies-format

[versions]
kotlin = "2.3.10"
kotlinxDatetime = "0.7.1"
kotlinxSerializationJSON = "1.9.0"
kotlinxCoroutines = "1.10.2"
protobuf = "4.33.4"
protobufPlugin = "0.9.4"
ktlint = "13.1.0"
dokka = "2.1.0"
buildconfig = "6.0.7"
mavenPublish = "0.36.0"
hoplite = "2.7.5"
slf4j = "2.0.17"
sl4jkotlinCoroutines = "1.10.2"
opentelemetry = "1.57.0"
logback = "1.5.6"
osdetector = "1.7.3"
jibExtensionApi = "0.4.0"

[libraries]
kotlinGradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlinGradlePluginApi = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin-api", version.ref = "kotlin" }
kotlinCompilerEmbeddable = { module = "org.jetbrains.kotlin:kotlin-compiler-embeddable", version.ref = "kotlin" }
kotlinxDatetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }
kotlinxSerialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJSON" }
kotlinxCoroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
kotlinxCoroutinesTest = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutines" }
protobufJava = { module = "com.google.protobuf:protobuf-java", version.ref = "protobuf" }
protobufJavaUtil = { module = "com.google.protobuf:protobuf-java-util", version.ref = "protobuf" }
protobufKotlin = { module = "com.google.protobuf:protobuf-kotlin", version.ref = "protobuf" }
hopliteCore = { module = "com.sksamuel.hoplite:hoplite-core", version.ref = "hoplite" }
hopliteYaml = { module = "com.sksamuel.hoplite:hoplite-yaml", version.ref = "hoplite" }
kotlinReflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
slf4jApi = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
slf4jSimple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }
kotlinCoroutinesSl4j = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-slf4j", version.ref = "sl4jkotlinCoroutines" }
opentelemetryApi = { module = "io.opentelemetry:opentelemetry-api", version.ref = "opentelemetry" }
opentelemetryExtensionKotlin = { module = "io.opentelemetry:opentelemetry-extension-kotlin", version.ref = "opentelemetry" }
opentelemetryContext = { module = "io.opentelemetry:opentelemetry-context", version.ref = "opentelemetry" }
opentelemetrySdk = { module = "io.opentelemetry:opentelemetry-sdk", version.ref = "opentelemetry" }
opentelemetrySdkTesting = { module = "io.opentelemetry:opentelemetry-sdk-testing", version.ref = "opentelemetry" }
opentelemetryExporterOtlp = { module = "io.opentelemetry:opentelemetry-exporter-otlp", version.ref = "opentelemetry" }
opentelemetryLogbackAppender = { module = "io.opentelemetry.instrumentation:opentelemetry-logback-appender-1.0", version = "2.25.0-alpha" }
logbackClassic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
jibGradlePluginExtensionApi = { module = "com.google.cloud.tools:jib-gradle-plugin-extension-api", version.ref = "jibExtensionApi" }

# Libraries can be bundled together for easier import
[bundles]
kotlinxEcosystem = ["kotlinxDatetime", "kotlinxSerialization", "kotlinxCoroutines"]
hoplite = ["hopliteCore", "hopliteYaml"]

[plugins]
kotlinPluginSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
protobuf = { id = "com.google.protobuf", version.ref = "protobufPlugin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
dokka-javadoc = { id = "org.jetbrains.dokka-javadoc", version.ref = "dokka" }
osdetector = { id = "com.google.osdetector", version.ref = "osdetector" }
